export {
  createClient,
  VagmiPlugin,
  VagmiPlugin as Plugin,
  useReadonlyClient as useClient,
} from './plugin';
export type {
  CreateClientConfig,
} from './plugin';

export {
  useAccount,
  useConnect,
  useDisconnect,
  useBalance,
  useProvider,
  useNetwork,
  useSwitchNetwork,
  useWebSocketProvider,
  useEnsName,
  useEnsAddress,
  useEnsResolver,
  useEnsAvatar,
  useBlockNumber,
  useFeeData,
  useSigner,
  useSignMessage,
  useSignTypedData,
  useWaitForTransaction,
} from './composables';

export {
  AddChainError,
  ChainDoesNotSupportMulticallError,
  ChainMismatchError,
  ChainNotConfiguredError,
  Client,
  Connector,
  ConnectorAlreadyConnectedError,
  ConnectorNotFoundError,
  ContractMethodDoesNotExistError,
  ContractMethodNoResultError,
  ContractMethodRevertedError,
  ContractResultDecodeError,
  ProviderChainsNotFound,
  ProviderRpcError,
  ResourceUnavailableError,
  RpcError,
  SwitchChainError,
  SwitchChainNotSupportedError,
  UserRejectedRequestError,
  configureChains,
  createStorage,
  deepEqual,
  deserialize,
  erc20ABI,
  erc4626ABI,
  erc721ABI,
  minimizeContractInterface,
  multicall,
  noopStorage,
  normalizeChainId,
  parseContractResult,
  prepareSendTransaction,
  prepareWriteContract,
  readContract,
  readContracts,
  sendTransaction,
  serialize,
  units,
  watchBlockNumber,
  watchContractEvent,
  watchMulticall,
  watchPendingTransactions,
  watchReadContract,
  watchReadContracts,
  writeContract,
} from '@wagmi/core';

export type {
  Chain,
  ChainProviderFn,
  ConnectorData,
  ConnectorEvents,
  Storage,
  Unit,
} from '@wagmi/core';

export type {
  QueryFunctionArgs,
  SetMaybeRef,
  QueryConfig,
  MutationConfig,
} from './types';
